version: '2'
services:
  gestion_invetarios-postgresql:
    image: postgres:11.6
    # volumes:
    #     - ~/volumes/jhipster/gestion_invetarios/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=gestion_invetarios
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
